version: "3.8"

services:
  backend:
    image: "muicharts-backend:latest"
    build:
      context: ./backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./persistence:/persistence
    environment:
      - "HTTPS_PORTS=443"
      - "LettuceEncrypt:AcceptTermsOfService=true"
      - "LettuceEncrypt:DomainNames:0=containers.xfox111.net"
      - "LettuceEncrypt:EmailAddress=eugene@xfox111.net"
